module.exports = {
   ADMIN_LOAD_USERS: "ADMIN_LOAD_USERS",
   ADMIN_LOAD_USERS_SUCCESS: "ADMIN_LOAD_USERS_SUCCESS",
   ADMIN_LOAD_USERS_FAIL: "ADMIN_LOAD_USERS_FAIL",

   ADMIN_LOAD_USER: "ADMIN_LOAD_USER",
   ADMIN_LOAD_USER_SUCCESS: "ADMIN_LOAD_USER_SUCCESS",
   ADMIN_LOAD_USER_FAIL: "ADMIN_LOAD_USER_FAIL",

   ADMIN_LOAD_SETTINGS: "ADMIN_LOAD_SETTINGS",
   ADMIN_LOAD_SETTINGS_SUCCESS: "ADMIN_LOAD_SETTINGS_SUCCESS",
   ADMIN_LOAD_SETTINGS_FAIL: "ADMIN_LOAD_SETTINGS_FAIL",

   ADMIN_SAVE_SETTINGS: "ADMIN_SAVE_SETTINGS",
   ADMIN_SAVE_SETTINGS_SUCCESS: "ADMIN_SAVE_SETTINGS_SUCCESS",
   ADMIN_SAVE_SETTINGS_FAIL: "ADMIN_SAVE_SETTINGS_FAIL",

   LOAD_PRINCIPAL_USER: "LOAD_PRINCIPAL_USER",
   LOAD_PRINCIPAL_USER_SUCCESS: "LOAD_PRINCIPAL_USER_SUCCESS",
   LOAD_PRINCIPAL_USER_FAIL: "LOAD_PRINCIPAL_USER_FAIL"
};

