require('bootstrap/less/bootstrap.less');
require("../css/bootstrap-theme.css");
require("../css/awesome-bootstrap-checkbox.css");
require("../css/formValidation.css");
require("../css/font-awesome.css");
require("../css/spinkit.css");
require("../css/animate.css");
require("../css/dropzone.min.css");
require("../scss/application-core.scss");
